// <auto-generated />
using System;
using GlobalOnlinebank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlobalOnlinebank.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108142453_Accounts 5")]
    partial class Accounts5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ContragentID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("ContragentID");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            AccountNumber = "KZ1000000001",
                            AccountType = 1,
                            Balance = 10000m,
                            ContragentID = -1L,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "KZT",
                            IsActive = true
                        },
                        new
                        {
                            Id = -2L,
                            AccountNumber = "KZ1000000002",
                            AccountType = 2,
                            Balance = 500m,
                            ContragentID = -1L,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "KZT",
                            IsActive = true
                        },
                        new
                        {
                            Id = -3L,
                            AccountNumber = "KZ1000000003",
                            AccountType = 1,
                            Balance = 20000m,
                            ContragentID = -1L,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Contragent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bin")
                        .HasColumnType("text");

                    b.Property<long?>("ContragentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<string>("KzName")
                        .HasColumnType("text");

                    b.Property<string>("RuName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContragentId");

                    b.ToTable("Contragents");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Bin = "961545123222",
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnName = "LLP Kolbasa",
                            IsActive = true,
                            IsNew = true,
                            KzName = "ТОО Колбаса",
                            RuName = "ТОО Колбаса"
                        },
                        new
                        {
                            Id = -2L,
                            Bin = "961545123251",
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnName = "LLP Rahat",
                            IsActive = true,
                            IsNew = true,
                            KzName = "ТОО Рахат",
                            RuName = "ТОО Рахат"
                        });
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Account", b =>
                {
                    b.HasOne("GlobalOnlinebank.Domain.Entities.Contragent", "Contragent")
                        .WithMany("Accounts")
                        .HasForeignKey("ContragentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contragent");
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Contragent", b =>
                {
                    b.HasOne("GlobalOnlinebank.Domain.Entities.Contragent", null)
                        .WithMany("Partners")
                        .HasForeignKey("ContragentId");
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Contragent", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Partners");
                });
#pragma warning restore 612, 618
        }
    }
}
