// <auto-generated />
using System;
using GlobalOnlinebank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlobalOnlinebank.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Contragent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bin")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<string>("KzName")
                        .HasColumnType("text");

                    b.Property<string>("RuName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Contragents");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Bin = "961545123222",
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnName = "LLP Kolbasa",
                            IsActive = true,
                            IsNew = true,
                            KzName = "ТОО Колбаса",
                            RuName = "ТОО Колбаса"
                        },
                        new
                        {
                            Id = -2L,
                            Bin = "961545123251",
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnName = "LLP Rahat",
                            IsActive = true,
                            IsNew = true,
                            KzName = "ТОО Рахат",
                            RuName = "ТОО Рахат"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
