// <auto-generated />
using System;
using GlobalOnlinebank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GlobalOnlinebank.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ContragentID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("ContragentID");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            AccountNumber = "KZ1000000001",
                            AccountType = 1,
                            Balance = 10000m,
                            ContragentID = -1L,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "KZT",
                            IsActive = true
                        },
                        new
                        {
                            Id = -2L,
                            AccountNumber = "KZ1000000002",
                            AccountType = 2,
                            Balance = 500m,
                            ContragentID = -1L,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "KZT",
                            IsActive = true
                        },
                        new
                        {
                            Id = -3L,
                            AccountNumber = "KZ1000000003",
                            AccountType = 1,
                            Balance = 20000m,
                            ContragentID = -1L,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Contragent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bin")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<string>("KzName")
                        .HasColumnType("text");

                    b.Property<decimal>("LoyaltyPoints")
                        .HasColumnType("numeric");

                    b.Property<string>("RuName")
                        .HasColumnType("text");

                    b.Property<long>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(-1L);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TariffId");

                    b.ToTable("Contragents");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Bin = "961545123222",
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnName = "LLP Kolbasa",
                            IsActive = true,
                            IsNew = true,
                            KzName = "ТОО Колбаса",
                            LoyaltyPoints = 0m,
                            RuName = "ТОО Колбаса",
                            TariffId = 0L
                        },
                        new
                        {
                            Id = -2L,
                            Bin = "961545123251",
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnName = "LLP Rahat",
                            IsActive = true,
                            IsNew = true,
                            KzName = "ТОО Рахат",
                            LoyaltyPoints = 0m,
                            RuName = "ТОО Рахат",
                            TariffId = 0L
                        });
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.ContragentPartner", b =>
                {
                    b.Property<long>("ContragentId")
                        .HasColumnType("bigint");

                    b.Property<long>("PartnerId")
                        .HasColumnType("bigint");

                    b.HasKey("ContragentId", "PartnerId");

                    b.HasIndex("PartnerId");

                    b.ToTable("ContragentPartners", (string)null);

                    b.HasData(
                        new
                        {
                            ContragentId = -1L,
                            PartnerId = -2L
                        },
                        new
                        {
                            ContragentId = -2L,
                            PartnerId = -1L
                        });
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Tariff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BonusPoints")
                        .HasColumnType("integer");

                    b.Property<decimal>("CommissionDiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasPersonalManager")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPriorityService")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<int>("MinPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("RateImprovementPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            BonusPoints = 0,
                            CommissionDiscountPercent = 0m,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "0–3000 баллов — стандартные условия",
                            HasPersonalManager = false,
                            HasPriorityService = false,
                            MaxPoints = 2999,
                            MinPoints = 0,
                            Name = "Base",
                            RateImprovementPercent = 0m
                        },
                        new
                        {
                            Id = -2L,
                            BonusPoints = 10000,
                            CommissionDiscountPercent = 3m,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "3000–6000 баллов — скидка 3%, бонус 10 000 баллов",
                            HasPersonalManager = false,
                            HasPriorityService = false,
                            MaxPoints = 5999,
                            MinPoints = 3000,
                            Name = "Prime",
                            RateImprovementPercent = 0m
                        },
                        new
                        {
                            Id = -3L,
                            BonusPoints = 20000,
                            CommissionDiscountPercent = 5m,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6000–8000 баллов — скидка 5%, бонус 20 000 баллов, улучшение курса +0.05%",
                            HasPersonalManager = false,
                            HasPriorityService = false,
                            MaxPoints = 7999,
                            MinPoints = 6000,
                            Name = "Prime PRO",
                            RateImprovementPercent = 0.05m
                        },
                        new
                        {
                            Id = -4L,
                            BonusPoints = 30000,
                            CommissionDiscountPercent = 7m,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "8000–10000 баллов — скидка 7%, бонус 30 000, приоритетная обработка",
                            HasPersonalManager = false,
                            HasPriorityService = true,
                            MaxPoints = 9999,
                            MinPoints = 8000,
                            Name = "Advance",
                            RateImprovementPercent = 0m
                        },
                        new
                        {
                            Id = -5L,
                            BonusPoints = 40000,
                            CommissionDiscountPercent = 10m,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "10 000–15 000 баллов — скидка 10%, бонус 40 000, персональный менеджер",
                            HasPersonalManager = true,
                            HasPriorityService = true,
                            MaxPoints = 14999,
                            MinPoints = 10000,
                            Name = "Executive",
                            RateImprovementPercent = 0.05m
                        },
                        new
                        {
                            Id = -6L,
                            BonusPoints = 50000,
                            CommissionDiscountPercent = 15m,
                            CreatedDate = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "15 000+ баллов — скидка 15%, бонус 50 000, полный пакет привилегий",
                            HasPersonalManager = true,
                            HasPriorityService = true,
                            MaxPoints = 2147483647,
                            MinPoints = 15000,
                            Name = "Privilege",
                            RateImprovementPercent = 0.1m
                        });
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("BonusAccountNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("BonusPointsEarned")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BonusPointsUsed")
                        .HasColumnType("numeric");

                    b.Property<string>("ComissionAccountNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("PaymentPurpose")
                        .HasColumnType("text");

                    b.Property<long?>("ReceiverAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReceiverAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("RecipientAddress")
                        .HasColumnType("text");

                    b.Property<string>("RecipientBankName")
                        .HasColumnType("text");

                    b.Property<string>("RecipientBankSwift")
                        .HasColumnType("text");

                    b.Property<string>("RecipientCity")
                        .HasColumnType("text");

                    b.Property<string>("RecipientCountry")
                        .HasColumnType("text");

                    b.Property<string>("RecipientName")
                        .HasColumnType("text");

                    b.Property<long>("SenderAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenderAccountNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverAccountId");

                    b.HasIndex("SenderAccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Account", b =>
                {
                    b.HasOne("GlobalOnlinebank.Domain.Entities.Contragent", "Contragent")
                        .WithMany("Accounts")
                        .HasForeignKey("ContragentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contragent");
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Contragent", b =>
                {
                    b.HasOne("GlobalOnlinebank.Domain.Entities.Tariff", "Tariff")
                        .WithMany("Contragents")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.ContragentPartner", b =>
                {
                    b.HasOne("GlobalOnlinebank.Domain.Entities.Contragent", "Contragent")
                        .WithMany()
                        .HasForeignKey("ContragentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalOnlinebank.Domain.Entities.Contragent", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contragent");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("GlobalOnlinebank.Domain.Entities.Account", "ReceiverAccount")
                        .WithMany()
                        .HasForeignKey("ReceiverAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GlobalOnlinebank.Domain.Entities.Account", "SenderAccount")
                        .WithMany()
                        .HasForeignKey("SenderAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceiverAccount");

                    b.Navigation("SenderAccount");
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Contragent", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("GlobalOnlinebank.Domain.Entities.Tariff", b =>
                {
                    b.Navigation("Contragents");
                });
#pragma warning restore 612, 618
        }
    }
}
